<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-06T16:58:44 IST" name="Suite" finished-at="2024-03-06T16:58:45 IST" duration-ms="1109">
    <groups>
    </groups>
    <test started-at="2024-03-06T16:58:44 IST" name="listdemo" finished-at="2024-03-06T16:58:45 IST" duration-ms="1109">
      <class name="com.listners.TestClass1">
        <test-method signature="test1()[pri:0, instance:com.listners.TestClass1@29215f06]" started-at="2024-03-06T16:58:44 IST" name="test1" finished-at="2024-03-06T16:58:44 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test2()[pri:0, instance:com.listners.TestClass1@29215f06]" started-at="2024-03-06T16:58:44 IST" name="test2" finished-at="2024-03-06T16:58:45 IST" duration-ms="1016" status="FAIL">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method com.listners.TestClass1.test2() didn't finish within the time-out 1000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.listners.TestClass1.test2() didn't finish within the time-out 1000
at java.base@17.0.9/java.lang.Thread.sleep(Native Method)
at app//com.listners.TestClass1.test2(TestClass1.java:15)
at java.base@17.0.9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.9/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.9/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.9/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method signature="test3()[pri:0, instance:com.listners.TestClass1@29215f06]" started-at="2024-03-06T16:58:45 IST" name="test3" finished-at="2024-03-06T16:58:45 IST" depends-on-methods="com.listners.TestClass1.test2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.listners.TestClass1.test3() on instance com.listners.TestClass1@29215f06 depends on not successfully finished methods 
[com.listners.TestClass1.test2() on instance com.listners.TestClass1@29215f06]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.listners.TestClass1.test3() on instance com.listners.TestClass1@29215f06 depends on not successfully finished methods 
[com.listners.TestClass1.test2() on instance com.listners.TestClass1@29215f06]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
      </class> <!-- com.listners.TestClass1 -->
    </test> <!-- listdemo -->
  </suite> <!-- Suite -->
</testng-results>
